library("shiny")
library("shinyjs")
library("sanssouci")
library("sanssouci.data")
library("plotly")
stopifnot(packageVersion("sanssouci.data") >= "0.5.0")
library("ggplot2")
library("dplyr")
library("htmlwidgets")
library("DT")
library("shinyBS")
library("stringr")
library("R.cache")
library("IIDEA")

IIDEA::app_ui()
